"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { HelpCircle } from "lucide-react";
import { AdminSecureShell } from "@/components/admin/secure-shell";
import { Button } from "@/components/ui/button";
import { useAuthStore } from "@/lib/store/auth";
import { useToast } from "@/components/ui/toast";
import { ADMIN_MFA_TOKEN_KEY } from "@/lib/admin-mfa-session";

export default function AdminMfaPage() {
  const [otp, setOtp] = useState<string[]>(Array(6).fill(""));
  const [verifying, setVerifying] = useState(false);
  const refs = useRef<(HTMLInputElement | null)[]>([]);
  const router = useRouter();
  const verifyAdminMfa = useAuthStore((s) => s.verifyAdminMfa);
  const { toast } = useToast();

  useEffect(() => {
    if (!sessionStorage.getItem(ADMIN_MFA_TOKEN_KEY)) {
      router.replace("/admin/login");
    }
  }, [router]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const mfaToken = sessionStorage.getItem(ADMIN_MFA_TOKEN_KEY);
    if (!mfaToken) {
      router.replace("/admin/login");
      return;
    }
    setVerifying(true);
    try {
      await verifyAdminMfa(mfaToken, otp.join(""));
      sessionStorage.removeItem(ADMIN_MFA_TOKEN_KEY);
      router.push("/admin/dashboard");
    } catch {
      toast({ title: "Invalid or expired code", description: "Please try again.", variant: "error" });
      setOtp(Array(6).fill(""));
      refs.current[0]?.focus();
    } finally {
      setVerifying(false);
    }
  };

  return (
    <AdminSecureShell badge="Two-Step Verification">
      <div className="mb-6 text-center">
        <h1 className="font-display text-2xl text-white">Two-Factor Auth</h1>
        <p className="mt-1.5 text-sm text-secure-500">Enter the security token generated by your mobile authenticator app</p>
      </div>

      <form onSubmit={handleSubmit} className="flex flex-col gap-6">
        <div className="flex justify-center gap-3">
          {otp.map((d, i) => (
            <input
              key={i}
              ref={(el) => {
                refs.current[i] = el;
              }}
              value={d}
              maxLength={1}
              inputMode="numeric"
              onChange={(e) => {
                const v = e.target.value.replace(/\D/g, "");
                const next = [...otp];
                next[i] = v;
                setOtp(next);
                if (v && i < 5) refs.current[i + 1]?.focus();
              }}
              onKeyDown={(e) => {
                if (e.key === "Backspace" && !otp[i] && i > 0) refs.current[i - 1]?.focus();
              }}
              className="h-14 w-14 rounded-sm border border-secure-700 bg-secure-800 text-center font-display text-2xl text-white focus:border-secure-accent focus:outline-none"
            />
          ))}
        </div>

        <div className="flex items-center justify-between text-xs text-secure-500">
          <span>Didn&apos;t receive a notification? Resend (59s)</span>
          <button type="button" className="font-medium text-secure-accent">
            Use a hardcopy emergency backup code
          </button>
        </div>

        <Button type="submit" size="lg" disabled={otp.some((d) => !d) || verifying} className="h-12 w-full">
          {verifying ? "Verifying…" : "Verify Identity & Launch"}
        </Button>
      </form>

      <div className="mt-6 flex items-center justify-center gap-2 text-xs text-secure-500">
        <HelpCircle className="size-4" />
        Locked out? Contact IT Support Desk: +91 80 2235 4400
      </div>
    </AdminSecureShell>
  );
}
